# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_choose(object):
    def setupUi(self, choose):
        choose.setObjectName("choose")
        choose.resize(640, 480)
        self.comboBox = QtWidgets.QComboBox(choose)
        self.comboBox.setGeometry(QtCore.QRect(70, 50, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.cscs = QtWidgets.QPushButton(choose)
        self.cscs.setGeometry(QtCore.QRect(380, 50, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cscs.setFont(font)
        self.cscs.setObjectName("cscs")

        self.retranslateUi(choose)
        QtCore.QMetaObject.connectSlotsByName(choose)

    def retranslateUi(self, choose):
        _translate = QtCore.QCoreApplication.translate
        choose.setWindowTitle(_translate("choose", "Dialog"))
        self.cscs.setText(_translate("choose", "选择班级"))
