# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hint.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Hi_Dialog(object):
    def setupUi(self, Hi_Dialog):
        Hi_Dialog.setObjectName("Hi_Dialog")
        Hi_Dialog.resize(491, 425)
        self.label = QtWidgets.QLabel(Hi_Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 171, 161))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/wenjianming.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Hi_Dialog)
        self.label_2.setGeometry(QtCore.QRect(220, 50, 241, 321))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/name.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.exit = QtWidgets.QPushButton(Hi_Dialog)
        self.exit.setGeometry(QtCore.QRect(20, 260, 141, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.exit.setFont(font)
        self.exit.setObjectName("exit")

        self.retranslateUi(Hi_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Hi_Dialog)

    def retranslateUi(self, Hi_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Hi_Dialog.setWindowTitle(_translate("Hi_Dialog", "Dialog"))
        self.exit.setText(_translate("Hi_Dialog", "确定"))
