# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'init.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_initDialog(object):
    def setupUi(self, initDialog):
        initDialog.setObjectName("initDialog")
        initDialog.resize(362, 191)
        self.label = QtWidgets.QLabel(initDialog)
        self.label.setGeometry(QtCore.QRect(50, 60, 281, 71))
        self.label.setObjectName("label")

        self.retranslateUi(initDialog)
        QtCore.QMetaObject.connectSlotsByName(initDialog)

    def retranslateUi(self, initDialog):
        _translate = QtCore.QCoreApplication.translate
        initDialog.setWindowTitle(_translate("initDialog", "Dialog"))
        self.label.setText(_translate("initDialog", "        第一次导入可能时间较长,请稍候"))
