# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'please.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PDialog(object):
    def setupUi(self, PDialog):
        PDialog.setObjectName("PDialog")
        PDialog.resize(340, 232)
        self.label = QtWidgets.QLabel(PDialog)
        self.label.setGeometry(QtCore.QRect(80, 20, 171, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.exit = QtWidgets.QPushButton(PDialog)
        self.exit.setGeometry(QtCore.QRect(110, 130, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.exit.setFont(font)
        self.exit.setObjectName("exit")

        self.retranslateUi(PDialog)
        QtCore.QMetaObject.connectSlotsByName(PDialog)

    def retranslateUi(self, PDialog):
        _translate = QtCore.QCoreApplication.translate
        PDialog.setWindowTitle(_translate("PDialog", "Dialog"))
        self.label.setText(_translate("PDialog", "请先选择班级"))
        self.exit.setText(_translate("PDialog", "确定"))
