# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_choose(object):
    def setupUi(self, choose):
        choose.setObjectName("choose")
        choose.resize(640, 480)
        font = QtGui.QFont()
        font.setPointSize(10)
        choose.setFont(font)
        self.comboBox = QtWidgets.QComboBox(choose)
        self.comboBox.setGeometry(QtCore.QRect(200, 40, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.cscs = QtWidgets.QPushButton(choose)
        self.cscs.setGeometry(QtCore.QRect(440, 40, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cscs.setFont(font)
        self.cscs.setObjectName("cscs")
        self.exit = QtWidgets.QPushButton(choose)
        self.exit.setGeometry(QtCore.QRect(410, 330, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.exit.setFont(font)
        self.exit.setObjectName("exit")
        self.suiji = QtWidgets.QPushButton(choose)
        self.suiji.setGeometry(QtCore.QRect(420, 170, 171, 81))
        self.suiji.setObjectName("suiji")
        self.textB = QtWidgets.QTextBrowser(choose)
        self.textB.setGeometry(QtCore.QRect(30, 170, 301, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textB.setFont(font)
        self.textB.setObjectName("textB")
        self.arrived = QtWidgets.QPushButton(choose)
        self.arrived.setGeometry(QtCore.QRect(30, 330, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.arrived.setFont(font)
        self.arrived.setObjectName("arrived")
        self.lack = QtWidgets.QPushButton(choose)
        self.lack.setGeometry(QtCore.QRect(170, 330, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lack.setFont(font)
        self.lack.setObjectName("lack")
        self.label = QtWidgets.QLabel(choose)
        self.label.setGeometry(QtCore.QRect(40, 30, 131, 101))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(choose)
        QtCore.QMetaObject.connectSlotsByName(choose)

    def retranslateUi(self, choose):
        _translate = QtCore.QCoreApplication.translate
        choose.setWindowTitle(_translate("choose", "Dialog"))
        self.cscs.setText(_translate("choose", "确定"))
        self.exit.setText(_translate("choose", "结束"))
        self.suiji.setText(_translate("choose", "随机选择一位幸运儿"))
        self.arrived.setText(_translate("choose", "已到"))
        self.lack.setText(_translate("choose", "缺课"))
        self.label.setText(_translate("choose", "请选择班级"))
