# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'have.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QDialog(object):
    def setupUi(self, QDialog):
        QDialog.setObjectName("QDialog")
        QDialog.resize(490, 303)
        self.label = QtWidgets.QLabel(QDialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 381, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.exit = QtWidgets.QPushButton(QDialog)
        self.exit.setGeometry(QtCore.QRect(100, 180, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.exit.setFont(font)
        self.exit.setObjectName("exit")

        self.retranslateUi(QDialog)
        QtCore.QMetaObject.connectSlotsByName(QDialog)

    def retranslateUi(self, QDialog):
        _translate = QtCore.QCoreApplication.translate
        QDialog.setWindowTitle(_translate("QDialog", "Dialog"))
        self.label.setText(_translate("QDialog", "班级信息已存在,强制导入会使信息丢失,如需要更新信息,请选择强制导入"))
        self.exit.setText(_translate("QDialog", "确定"))
