# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'name.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_name(object):
    def setupUi(self, name):
        name.setObjectName("name")
        name.resize(640, 400)
        name.setSizeGripEnabled(False)
        self.file = QtWidgets.QPushButton(name)
        self.file.setGeometry(QtCore.QRect(450, 20, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.file.setFont(font)
        self.file.setObjectName("file")
        self.label = QtWidgets.QLabel(name)
        self.label.setGeometry(QtCore.QRect(50, 30, 361, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(name)
        self.label_2.setGeometry(QtCore.QRect(50, 180, 351, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(name)
        self.pushButton.setGeometry(QtCore.QRect(440, 200, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.file_2 = QtWidgets.QPushButton(name)
        self.file_2.setGeometry(QtCore.QRect(450, 90, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.file_2.setFont(font)
        self.file_2.setObjectName("file_2")
        self.exit = QtWidgets.QPushButton(name)
        self.exit.setGeometry(QtCore.QRect(440, 300, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.exit.setFont(font)
        self.exit.setObjectName("exit")
        self.view = QtWidgets.QPushButton(name)
        self.view.setGeometry(QtCore.QRect(40, 120, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.view.setFont(font)
        self.view.setObjectName("view")

        self.retranslateUi(name)
        QtCore.QMetaObject.connectSlotsByName(name)

    def retranslateUi(self, name):
        _translate = QtCore.QCoreApplication.translate
        name.setWindowTitle(_translate("name", "Dialog"))
        self.file.setText(_translate("name", "导入信息"))
        self.label.setText(_translate("name", "请选择班级excel(需包含学号以及姓名)"))
        self.label_2.setText(_translate("name", "班级信息已到入导入"))
        self.pushButton.setText(_translate("name", "开始点名"))
        self.file_2.setText(_translate("name", "强制导入"))
        self.exit.setText(_translate("name", "退出"))
        self.view.setText(_translate("name", "点我查看模板"))
