# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'no_mate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_no_Dialog(object):
    def setupUi(self, no_Dialog):
        no_Dialog.setObjectName("no_Dialog")
        no_Dialog.resize(517, 337)
        font = QtGui.QFont()
        font.setPointSize(18)
        no_Dialog.setFont(font)
        self.label = QtWidgets.QLabel(no_Dialog)
        self.label.setGeometry(QtCore.QRect(100, 40, 331, 111))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.exit = QtWidgets.QPushButton(no_Dialog)
        self.exit.setGeometry(QtCore.QRect(120, 190, 241, 101))
        self.exit.setObjectName("exit")

        self.retranslateUi(no_Dialog)
        QtCore.QMetaObject.connectSlotsByName(no_Dialog)

    def retranslateUi(self, no_Dialog):
        _translate = QtCore.QCoreApplication.translate
        no_Dialog.setWindowTitle(_translate("no_Dialog", "Dialog"))
        self.label.setText(_translate("no_Dialog", "您还没有开始点名"))
        self.exit.setText(_translate("no_Dialog", "确定"))
